
service: atm-finder

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-2
  role: arn:aws:iam::631072867253:role/lambda_basic_execution

functions:
  firstRun:
    handler: handler.firstRun

  findGeoCode:
    handler: handler.findGeoCode

  pushToAlgolia:
    handler: handler.pushToAlgolia

  locationFailed:
    handler: handler.locationFailed

  pickSingle:
    handler: handler.pickSingle
    events:
      - stream: arn:aws:dynamodb:us-east-2:631072867253:table/location-list/stream/2018-01-17T12:31:57.687
        batchSize: 1
        startingPosition: LATEST
        enabled: true

  findLocations:
    handler: handler.findLocations
    events:
      - http:
          cors: true
          path: locations
          method: get
          private: false
